import json
from database import SessionLocal, init_db, MovieDB

MOVIES = [
    # ==================== ACTION (12) ====================
    {
        "title": "The Dark Knight",
        "year": 2008,
        "director": "Christopher Nolan",
        "cast": "Christian Bale, Heath Ledger, Aaron Eckhart",
        "genres": "Action,Thriller",
        "language": "English",
        "duration_minutes": 152,
        "rating": 9.0,
        "synopsis": "When the menace known as the Joker wreaks havoc on Gotham, Batman must confront one of the greatest psychological tests of his ability to fight injustice.",
        "streaming_platforms": "Netflix,HBO Max,Amazon Prime",
        "poster_url": "https://image.tmdb.org/t/p/w500/qJ2tW6WMUDux911M5nRQYqFGqLi.jpg"
    },
    {
        "title": "Mad Max: Fury Road",
        "year": 2015,
        "director": "George Miller",
        "cast": "Tom Hardy, Charlize Theron, Nicholas Hoult",
        "genres": "Action,Sci-Fi",
        "language": "English",
        "duration_minutes": 120,
        "rating": 8.1,
        "synopsis": "In a post-apocalyptic wasteland, a woman rebels against a tyrannical ruler with the help of a group of female prisoners and a drifter named Max.",
        "streaming_platforms": "HBO Max,Amazon Prime,Hulu",
        "poster_url": "https://image.tmdb.org/t/p/w500/8tZYtuWezp8JbcsvHYO0O46tFBo.jpg"
    },
    {
        "title": "John Wick",
        "year": 2014,
        "director": "Chad Stahelski",
        "cast": "Keanu Reeves, Michael Nyqvist, Alfie Allen",
        "genres": "Action,Thriller",
        "language": "English",
        "duration_minutes": 101,
        "rating": 7.4,
        "synopsis": "An ex-hitman comes out of retirement to track down the gangsters that killed his dog and took everything from him.",
        "streaming_platforms": "Netflix,Amazon Prime,Hulu",
        "poster_url": "https://image.tmdb.org/t/p/w500/1ZbXnVPM2T6Mx3RJv9lzP1XRMag.jpg"
    },
    {
        "title": "Gladiator",
        "year": 2000,
        "director": "Ridley Scott",
        "cast": "Russell Crowe, Joaquin Phoenix, Connie Nielsen",
        "genres": "Action,Drama",
        "language": "English",
        "duration_minutes": 155,
        "rating": 8.5,
        "synopsis": "A former Roman General sets out to exact vengeance against the emperor who murdered his family and sent him into slavery.",
        "streaming_platforms": "Amazon Prime,Paramount+,Apple TV",
        "poster_url": "https://image.tmdb.org/t/p/w500/ty8TGRuvJLPUmAR1H1nRIsgCLvV.jpg"
    },
    {
        "title": "Baahubali: The Beginning",
        "year": 2015,
        "director": "S.S. Rajamouli",
        "cast": "Prabhas, Rana Daggubati, Anushka Shetty",
        "genres": "Action,Drama",
        "language": "Telugu",
        "duration_minutes": 159,
        "rating": 8.1,
        "synopsis": "A man in captivity discovers his heroic lineage and sets out to reclaim his rightful throne from a tyrannical ruler.",
        "streaming_platforms": "Amazon Prime,Netflix,Disney+ Hotstar",
        "poster_url": "https://image.tmdb.org/t/p/w500/uDhnzOHKfFdb2jG5zn8JuXoU8nV.jpg"
    },
    {
        "title": "RRR",
        "year": 2022,
        "director": "S.S. Rajamouli",
        "cast": "Ram Charan, Jr. NTR, Alia Bhatt",
        "genres": "Action,Drama",
        "language": "Telugu",
        "duration_minutes": 187,
        "rating": 7.8,
        "synopsis": "A fictitious story about two legendary Indian revolutionaries and their journey away from joining forces to save India from British rule.",
        "streaming_platforms": "Netflix,Disney+ Hotstar",
        "poster_url": "https://image.tmdb.org/t/p/w500/dhMjNhAGHymACMdrcR2hwp5ymQy.jpg"
    },
    {
        "title": "Die Hard",
        "year": 1988,
        "director": "John McTiernan",
        "cast": "Bruce Willis, Alan Rickman, Bonnie Bedelia",
        "genres": "Action,Thriller",
        "language": "English",
        "duration_minutes": 132,
        "rating": 8.2,
        "synopsis": "An NYPD officer tries to save his wife and several others taken hostage by German terrorists during a Christmas party.",
        "streaming_platforms": "Hulu,Amazon Prime,Paramount+",
        "poster_url": "https://image.tmdb.org/t/p/w500/7FzgYTgC1Tmvl4xY5e1gdN7gMnb.jpg"
    },
    {
        "title": "K.G.F: Chapter 1",
        "year": 2018,
        "director": "Prashanth Neel",
        "cast": "Yash, Srinidhi Shetty, Ramachandra Raju",
        "genres": "Action,Drama",
        "language": "Kannada",
        "duration_minutes": 156,
        "rating": 8.3,
        "synopsis": "A gangster's rise to power in the gold mines of Kolar Gold Fields, defying a tyrannical ruler who controls the region.",
        "streaming_platforms": "Amazon Prime,Netflix",
        "poster_url": "https://image.tmdb.org/t/p/w500/jKy74w9hF9icjEzSs2KQLc4KSKi.jpg"
    },
    {
        "title": "The Raid: Redemption",
        "year": 2011,
        "director": "Gareth Evans",
        "cast": "Iko Uwais, Joe Taslim, Donny Alamsyah",
        "genres": "Action,Thriller",
        "language": "Indonesian",
        "duration_minutes": 101,
        "rating": 7.6,
        "synopsis": "A SWAT team becomes trapped in a 15-story run-down apartment building ruled by a crime lord and his army of thugs.",
        "streaming_platforms": "Netflix,Amazon Prime",
        "poster_url": "https://image.tmdb.org/t/p/w500/bHfjXN06PVJtL34qDj8AghzM2yn.jpg"
    },
    {
        "title": "Top Gun: Maverick",
        "year": 2022,
        "director": "Joseph Kosinski",
        "cast": "Tom Cruise, Miles Teller, Jennifer Connelly",
        "genres": "Action,Drama",
        "language": "English",
        "duration_minutes": 131,
        "rating": 8.3,
        "synopsis": "After more than thirty years of service, Maverick confronts his past while training a new generation of pilots for an impossible mission.",
        "streaming_platforms": "Paramount+,Amazon Prime",
        "poster_url": "https://image.tmdb.org/t/p/w500/62HCnUTziyWcpDaBO2i1DG290sA.jpg"
    },
    {
        "title": "Infernal Affairs",
        "year": 2002,
        "director": "Andrew Lau, Alan Mak",
        "cast": "Andy Lau, Tony Leung, Eric Tsang",
        "genres": "Action,Thriller",
        "language": "Cantonese",
        "duration_minutes": 101,
        "rating": 8.0,
        "synopsis": "A cop on the gangster payroll and a mole in the police force try to identify each other before their covers are blown.",
        "streaming_platforms": "Netflix,Viki",
        "poster_url": "https://image.tmdb.org/t/p/w500/xXb9EjXcOkMeoQcYtIHjKMAqfEH.jpg"
    },
    {
        "title": "Escape Room",
        "year": 2019,
        "director": "Adam Robitel",
        "cast": "Taylor Russell, Logan Miller, Deborah Ann Woll",
        "genres": "Action,Thriller",
        "language": "English",
        "duration_minutes": 100,
        "rating": 6.4,
        "synopsis": "Six strangers find themselves in circumstances beyond their control and must use their wits to survive.",
        "streaming_platforms": "Netflix,Amazon Prime",
        "poster_url": "https://image.tmdb.org/t/p/w500/oKxVvJinSOgTBiBqNpJEHov0YAr.jpg"
    },

    # ==================== COMEDY (12) ====================
    {
        "title": "3 Idiots",
        "year": 2009,
        "director": "Rajkumar Hirani",
        "cast": "Aamir Khan, R. Madhavan, Sharman Joshi",
        "genres": "Comedy,Drama",
        "language": "Hindi",
        "duration_minutes": 170,
        "rating": 8.4,
        "synopsis": "Two friends embark on a quest for a lost buddy and encounter their college friend who they believed had left the country long ago.",
        "streaming_platforms": "Netflix,Amazon Prime,Disney+ Hotstar",
        "poster_url": "https://image.tmdb.org/t/p/w500/wdJBr95AA4q2vDP4KGS7oYJ6mPY.jpg"
    },
    {
        "title": "Superbad",
        "year": 2007,
        "director": "Greg Mottola",
        "cast": "Jonah Hill, Michael Cera, Christopher Mintz-Plasse",
        "genres": "Comedy",
        "language": "English",
        "duration_minutes": 113,
        "rating": 7.6,
        "synopsis": "Two co-dependent high school seniors are forced to deal with separation anxiety after their plan to stage a party goes awry.",
        "streaming_platforms": "Netflix,Hulu",
        "poster_url": "https://image.tmdb.org/t/p/w500/d5iIlFn5s0ImszYzBPb8JPIfbXD.jpg"
    },
    {
        "title": "The Grand Budapest Hotel",
        "year": 2014,
        "director": "Wes Anderson",
        "cast": "Ralph Fiennes, F. Murray Abraham, Mathieu Amalric",
        "genres": "Comedy,Drama",
        "language": "English",
        "duration_minutes": 99,
        "rating": 8.1,
        "synopsis": "A writer encounters the owner of an aging high-class hotel, who tells him of his early years serving as a lobby boy under the hotel's legendary concierge.",
        "streaming_platforms": "Disney+,Hulu",
        "poster_url": "https://image.tmdb.org/t/p/w500/eWdyYQreja6JGCzqHWXpWHDrrPo.jpg"
    },
    {
        "title": "Hera Pheri",
        "year": 2000,
        "director": "Priyadarshan",
        "cast": "Akshay Kumar, Paresh Rawal, Suniel Shetty",
        "genres": "Comedy",
        "language": "Hindi",
        "duration_minutes": 156,
        "rating": 8.1,
        "synopsis": "Three men become unwitting participants in a kidnapping plot when one of them answers a wrong number and a ransom is promised.",
        "streaming_platforms": "Amazon Prime,Zee5",
        "poster_url": "https://image.tmdb.org/t/p/w500/dBxxtfKwMYJFhS7YD7gKxvZfQq.jpg"
    },
    {
        "title": "Parasite",
        "year": 2019,
        "director": "Bong Joon-ho",
        "cast": "Song Kang-ho, Lee Sun-kyun, Cho Yeo-jeong",
        "genres": "Comedy,Thriller",
        "language": "Korean",
        "duration_minutes": 132,
        "rating": 8.5,
        "synopsis": "Greed and class discrimination threaten the newly formed symbiotic relationship between the wealthy Park family and the destitute Kim clan.",
        "streaming_platforms": "Hulu,Amazon Prime",
        "poster_url": "https://image.tmdb.org/t/p/w500/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg"
    },
    {
        "title": "The Hangover",
        "year": 2009,
        "director": "Todd Phillips",
        "cast": "Zach Galifianakis, Bradley Cooper, Justin Bartha",
        "genres": "Comedy",
        "language": "English",
        "duration_minutes": 100,
        "rating": 7.7,
        "synopsis": "Three buddies wake up from a bachelor party in Vegas with no memory and the bachelor missing. They make their way around the city trying to find him.",
        "streaming_platforms": "HBO Max,Amazon Prime",
        "poster_url": "https://image.tmdb.org/t/p/w500/A0q8L9pLq0ebLUE0TG8Tb5MY1lW.jpg"
    },
    {
        "title": "Panchayat",
        "year": 2020,
        "director": "Deepak Kumar Mishra",
        "cast": "Jitendra Kumar, Raghubir Yadav, Neena Gupta",
        "genres": "Comedy,Drama",
        "language": "Hindi",
        "duration_minutes": 30,
        "rating": 8.9,
        "synopsis": "An engineering graduate reluctantly takes a government job as secretary of a panchayat office in a remote village of Uttar Pradesh.",
        "streaming_platforms": "Amazon Prime",
        "poster_url": "https://image.tmdb.org/t/p/w500/tVKI1YkDLn3aObeFHKzMFdAq7xD.jpg"
    },
    {
        "title": "What We Do in the Shadows",
        "year": 2014,
        "director": "Jemaine Clement, Taika Waititi",
        "cast": "Jemaine Clement, Taika Waititi, Jonathan Brugh",
        "genres": "Comedy",
        "language": "English",
        "duration_minutes": 85,
        "rating": 7.6,
        "synopsis": "A documentary-style comedy that follows the lives of four vampire roommates trying to cope with the modern world.",
        "streaming_platforms": "Hulu,Amazon Prime",
        "poster_url": "https://image.tmdb.org/t/p/w500/lN3v40eJbSN0jM3gWyGdA3xKzGR.jpg"
    },
    {
        "title": "Crazy Rich Asians",
        "year": 2018,
        "director": "Jon M. Chu",
        "cast": "Constance Wu, Henry Golding, Michelle Yeoh",
        "genres": "Comedy,Romance",
        "language": "English",
        "duration_minutes": 120,
        "rating": 7.0,
        "synopsis": "An economics professor accompanies her boyfriend to his best friend's wedding in Singapore and is surprised to learn of his family's extreme wealth.",
        "streaming_platforms": "HBO Max,Amazon Prime",
        "poster_url": "https://image.tmdb.org/t/p/w500/1XxL4Ns2d5w4JL2S8NXFq2Ff2iR.jpg"
    },
    {
        "title": "Golmaal: Fun Unlimited",
        "year": 2006,
        "director": "Rohit Shetty",
        "cast": "Ajay Devgn, Sharman Joshi, Tusshar Kapoor",
        "genres": "Comedy",
        "language": "Hindi",
        "duration_minutes": 150,
        "rating": 7.4,
        "synopsis": "Four men con a blind man out of his property, only to have their schemes backfire in hilarious ways.",
        "streaming_platforms": "Amazon Prime,Netflix",
        "poster_url": "https://image.tmdb.org/t/p/w500/pJu7YqPFM0i5s9pFbRf2nJXwEiV.jpg"
    },
    {
        "title": "Hunt for the Wilderpeople",
        "year": 2016,
        "director": "Taika Waititi",
        "cast": "Sam Neill, Julian Dennison, Rima Te Wiata",
        "genres": "Comedy,Adventure",
        "language": "English",
        "duration_minutes": 101,
        "rating": 7.8,
        "synopsis": "A ragtag group of misfits goes on the run in the New Zealand bush after one of them is wrongly accused of murder.",
        "streaming_platforms": "Netflix,Hulu",
        "poster_url": "https://image.tmdb.org/t/p/w500/yXNgE7f0Fq1VwKgP8Y9KqGj3SfI.jpg"
    },
    {
        "title": "Welcome",
        "year": 2007,
        "director": "Anees Bazmee",
        "cast": "Akshay Kumar, Nana Patekar, Anil Kapoor",
        "genres": "Comedy",
        "language": "Hindi",
        "duration_minutes": 158,
        "rating": 7.5,
        "synopsis": "A man is tasked with welcoming his fiancée's brother who turns out to be a gangster, leading to a series of comical misunderstandings.",
        "streaming_platforms": "Amazon Prime,Disney+ Hotstar",
        "poster_url": "https://image.tmdb.org/t/p/w500/3gBJJFqKzEYR3jX4aY4J3nJBmHS.jpg"
    },

    # ==================== DRAMA (12) ====================
    {
        "title": "The Shawshank Redemption",
        "year": 1994,
        "director": "Frank Darabont",
        "cast": "Tim Robbins, Morgan Freeman, Bob Gunton",
        "genres": "Drama",
        "language": "English",
        "duration_minutes": 142,
        "rating": 9.3,
        "synopsis": "Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.",
        "streaming_platforms": "Netflix,Amazon Prime",
        "poster_url": "https://image.tmdb.org/t/p/w500/9cjIGRiQoRCgTNEMmcoADqwiAoq.jpg"
    },
    {
        "title": "Forrest Gump",
        "year": 1994,
        "director": "Robert Zemeckis",
        "cast": "Tom Hanks, Robin Wright, Gary Sinise",
        "genres": "Drama,Romance",
        "language": "English",
        "duration_minutes": 142,
        "rating": 8.8,
        "synopsis": "The story of a man with a low IQ who accomplished great things in his life and was present during some of the most iconic events in American history.",
        "streaming_platforms": "Paramount+,Amazon Prime",
        "poster_url": "https://image.tmdb.org/t/p/w500/arw2vcBveWOVZr6pxd9XTd1TdQa.jpg"
    },
    {
        "title": "Schindler's List",
        "year": 1993,
        "director": "Steven Spielberg",
        "cast": "Liam Neeson, Ralph Fiennes, Ben Kingsley",
        "genres": "Drama,History",
        "language": "English",
        "duration_minutes": 195,
        "rating": 9.0,
        "synopsis": "In German-occupied Poland during World War II, Oskar Schindler becomes concerned for his Jewish workforce after witnessing their persecution.",
        "streaming_platforms": "Amazon Prime,Peacock",
        "poster_url": "https://image.tmdb.org/t/p/w500/sF1U4EUQS8YHUYjNl3pMGNIQyr0.jpg"
    },
    {
        "title": "Piku",
        "year": 2015,
        "director": "Shoojit Sircar",
        "cast": "Deepika Padukone, Amitabh Bachhan, Irrfan Khan",
        "genres": "Drama,Comedy",
        "language": "Hindi",
        "duration_minutes": 133,
        "rating": 7.6,
        "synopsis": "A quirky comedy about the relationship between a daughter and her aging father who is obsessed with his bowel movements.",
        "streaming_platforms": "Amazon Prime,Netflix",
        "poster_url": "https://image.tmdb.org/t/p/w500/lfJGh5oYb9kTF0Y9HjKq7r3J6OJ.jpg"
    },
    {
        "title": "The Green Mile",
        "year": 1999,
        "director": "Frank Darabont",
        "cast": "Tom Hanks, Michael Clarke Duncan, David Morse",
        "genres": "Drama,Fantasy",
        "language": "English",
        "duration_minutes": 189,
        "rating": 8.6,
        "synopsis": "The lives of guards on Death Row are affected by one of their charges: a gentle giant with a mysterious gift.",
        "streaming_platforms": "Netflix,Amazon Prime",
        "poster_url": "https://image.tmdb.org/t/p/w500/velVJ0lfyp92Y2BE12Ih0g4V9Cq.jpg"
    },
    {
        "title": "12 Years a Slave",
        "year": 2013,
        "director": "Steve McQueen",
        "cast": "Chiwetel Ejiofor, Michael Fassbender, Lupita Nyong'o",
        "genres": "Drama,History",
        "language": "English",
        "duration_minutes": 134,
        "rating": 8.1,
        "synopsis": "A free-born African American man is kidnapped and sold into slavery, enduring years of brutality before finding an opportunity to seek help.",
        "streaming_platforms": "Hulu,Amazon Prime",
        "poster_url": "https://image.tmdb.org/t/p/w500/yj8LbTju1p5MfkZTwitJMYeMPOx.jpg"
    },
    {
        "title": "The Pursuit of Happyness",
        "year": 2006,
        "director": "Gabriele Muccino",
        "cast": "Will Smith, Jaden Smith, Thandiwe Newton",
        "genres": "Drama",
        "language": "English",
        "duration_minutes": 117,
        "rating": 8.0,
        "synopsis": "A homeless father battles to establish a better life for his young son while maintaining his dignity and hope.",
        "streaming_platforms": "Netflix,Amazon Prime",
        "poster_url": "https://image.tmdb.org/t/p/w500/iKDQeFpbSvjU2Xzpg0am308mxkx.jpg"
    },
    {
        "title": "Drishyam",
        "year": 2013,
        "director": "Jeethu Joseph",
        "cast": "Mohanlal, Meena, Asha Sarath",
        "genres": "Drama,Thriller",
        "language": "Malayalam",
        "duration_minutes": 160,
        "rating": 8.3,
        "synopsis": "A man goes to great lengths to protect his family after they commit an accidental crime, outsmarting the police at every turn.",
        "streaming_platforms": "Amazon Prime,Netflix",
        "poster_url": "https://image.tmdb.org/t/p/w500/kRFnOdGMbxFsBfPtH5Ks2cM3KcI.jpg"
    },
    {
        "title": "The Pianist",
        "year": 2002,
        "director": "Roman Polanski",
        "cast": "Adrien Brody, Thomas Kretschmann, Frank Finlay",
        "genres": "Drama,History",
        "language": "English",
        "duration_minutes": 150,
        "rating": 8.5,
        "synopsis": "A Polish-Jewish pianist struggles to survive the destruction of the Warsaw ghetto during World War II.",
        "streaming_platforms": "Amazon Prime,Paramount+",
        "poster_url": "https://image.tmdb.org/t/p/w500/p66kMblMdFl5JqSH3sH3VsRbHmf.jpg"
    },
    {
        "title": "The Farewell",
        "year": 2019,
        "director": "Lulu Wang",
        "cast": "Awkwafina, Tzi Ma, Diana Lin",
        "genres": "Drama,Comedy",
        "language": "English",
        "duration_minutes": 100,
        "rating": 7.5,
        "synopsis": "A Chinese family discovers their grandmother has only a short while left to live and decide to keep her in the dark, scheduling a family gathering before she passes.",
        "streaming_platforms": "Amazon Prime,Hulu",
        "poster_url": "https://image.tmdb.org/t/p/w500/tyf6PjdMbYGbN3GhBPPHLWB9uBC.jpg"
    },
    {
        "title": "Masaan",
        "year": 2015,
        "director": "Neeraj Ghaywan",
        "cast": "Richa Chadha, Vicky Kaushal, Sanjay Mishra",
        "genres": "Drama,Romance",
        "language": "Hindi",
        "duration_minutes": 99,
        "rating": 7.5,
        "synopsis": "Two stories of love and social stigma unfold in Varanasi, exploring caste discrimination and the struggle for dignity.",
        "streaming_platforms": "Amazon Prime,Netflix",
        "poster_url": "https://image.tmdb.org/t/p/w500/oJFv6bCflKJmk1d5m6Gq3VXePJf.jpg"
    },
    {
        "title": "Moonlight",
        "year": 2016,
        "director": "Barry Jenkins",
        "cast": "Trevante Rhodes, Andre Holland, Janelle Monáe",
        "genres": "Drama",
        "language": "English",
        "duration_minutes": 111,
        "rating": 7.4,
        "synopsis": "A young African-American man grapples with his identity and sexuality while experiencing the everyday struggles of childhood, adolescence, and burgeoning adulthood.",
        "streaming_platforms": "Amazon Prime,Hulu",
        "poster_url": "https://image.tmdb.org/t/p/w500/4911T5FbJ9eD2Faz5Z8cT3SUhU3.jpg"
    },

    # ==================== THRILLER (12) ====================
    {
        "title": "Shutter Island",
        "year": 2010,
        "director": "Martin Scorsese",
        "cast": "Leonardo DiCaprio, Mark Ruffalo, Ben Kingsley",
        "genres": "Thriller,Mystery",
        "language": "English",
        "duration_minutes": 138,
        "rating": 8.2,
        "synopsis": "A U.S. Marshal investigates the disappearance of a murderer who escaped from a hospital for the criminally insane.",
        "streaming_platforms": "Netflix,Paramount+",
        "poster_url": "https://image.tmdb.org/t/p/w500/kve20tXwUZpu4GUX1lJZ8MfSTt.jpg"
    },
    {
        "title": "Gone Girl",
        "year": 2014,
        "director": "David Fincher",
        "cast": "Ben Affleck, Rosamund Pike, Neil Patrick Harris",
        "genres": "Thriller,Mystery",
        "language": "English",
        "duration_minutes": 149,
        "rating": 8.1,
        "synopsis": "With his wife's disappearance having become the focus of an intense media circus, a man sees the spotlight turned on him when it's suspected he may not be innocent.",
        "streaming_platforms": "Amazon Prime,Hulu",
        "poster_url": "https://image.tmdb.org/t/p/w500/gdiLTof3rbPDAmPaCf4g3NWjKbJ.jpg"
    },
    {
        "title": "Zodiac",
        "year": 2007,
        "director": "David Fincher",
        "cast": "Jake Gyllenhaal, Robert Downey Jr., Mark Ruffalo",
        "genres": "Thriller,Mystery",
        "language": "English",
        "duration_minutes": 157,
        "rating": 7.7,
        "synopsis": "A cartoonist becomes an amateur detective obsessed with tracking down the Zodiac Killer, an unidentified individual who murders people in Northern California.",
        "streaming_platforms": "Paramount+,Amazon Prime",
        "poster_url": "https://image.tmdb.org/t/p/w500/lSrsRkYANbVMY2GqjPi0iHRxoG3.jpg"
    },
    {
        "title": "Drishyam",
        "year": 2015,
        "director": "Nishikant Kamat",
        "cast": "Ajay Devgn, Tabu, Shriya Saran",
        "genres": "Thriller,Drama",
        "language": "Hindi",
        "duration_minutes": 163,
        "rating": 8.2,
        "synopsis": "A man goes to great lengths to cover up a crime committed by his family, outsmarting a determined police inspector.",
        "streaming_platforms": "Amazon Prime,Netflix",
        "poster_url": "https://image.tmdb.org/t/p/w500/7KNaV0cHjq2wSNjO3YqXNfMHMbK.jpg"
    },
    {
        "title": "Memories of Murder",
        "year": 2003,
        "director": "Bong Joon-ho",
        "cast": "Song Kang-ho, Kim Sang-kyung, Kim Roi-ha",
        "genres": "Thriller,Crime",
        "language": "Korean",
        "duration_minutes": 132,
        "rating": 8.1,
        "synopsis": "In a small Korean province in 1986, two detectives struggle to solve a series of brutal murders that follow the same pattern.",
        "streaming_platforms": "Amazon Prime,Hulu",
        "poster_url": "https://image.tmdb.org/t/p/w500/nb3xI8XI3w4pMVZ38VijbsyBqP4.jpg"
    },
    {
        "title": "A Wednesday",
        "year": 2008,
        "director": "Neeraj Pandey",
        "cast": "Naseeruddin Shah, Anupam Kher, Jimmy Sheirgill",
        "genres": "Thriller,Crime",
        "language": "Hindi",
        "duration_minutes": 98,
        "rating": 8.1,
        "synopsis": "A common man orchestrates a series of bomb blasts across the city to demand the release of four terrorists, keeping the entire police force on its toes.",
        "streaming_platforms": "Amazon Prime,Netflix",
        "poster_url": "https://image.tmdb.org/t/p/w500/x9Yc7FYr0LqX2JLwHq4U3sNqIgQ.jpg"
    },
    {
        "title": "Se7en",
        "year": 1995,
        "director": "David Fincher",
        "cast": "Brad Pitt, Morgan Freeman, Kevin Spacey",
        "genres": "Thriller,Crime",
        "language": "English",
        "duration_minutes": 127,
        "rating": 8.6,
        "synopsis": "Two detectives hunt a serial killer who uses the seven deadly sins as his motives, uncovering a twisted and macabre plan.",
        "streaming_platforms": "Netflix,Amazon Prime",
        "poster_url": "https://image.tmdb.org/t/p/w500/6yoghtyTpznpBik8EngEmJskVUO.jpg"
    },
    {
        "title": "Oldboy",
        "year": 2003,
        "director": "Park Chan-wook",
        "cast": "Choi Min-sik, Yoo Ji-tae, Kang Hye-jung",
        "genres": "Thriller,Mystery",
        "language": "Korean",
        "duration_minutes": 120,
        "rating": 8.4,
        "synopsis": "After being kidnapped and imprisoned for 15 years, Oh Dae-su is released and begins to seek revenge on his captor.",
        "streaming_platforms": "Amazon Prime,Hulu",
        "poster_url": "https://image.tmdb.org/t/p/w500/pXyQ0l8TbS6MX5I4Gn3bvmW3FwY.jpg"
    },
    {
        "title": "Rang De Basanti",
        "year": 2006,
        "director": "Rakeysh Omprakash Mehra",
        "cast": "Aamir Khan, Soha Ali Khan, Madhavan",
        "genres": "Thriller,Drama",
        "language": "Hindi",
        "duration_minutes": 167,
        "rating": 8.2,
        "synopsis": "A British filmmaker comes to India to make a film about Indian revolutionaries, inspiring a group of college students to take up a similar cause.",
        "streaming_platforms": "Amazon Prime,Netflix",
        "poster_url": "https://image.tmdb.org/t/p/w500/sGJlGMPg2q2sH3Jv3kx7jJ8qFVz.jpg"
    },
    {
        "title": "The Silence of the Lambs",
        "year": 1991,
        "director": "Jonathan Demme",
        "cast": "Jodie Foster, Anthony Hopkins, Lawrence A. Bonney",
        "genres": "Thriller,Crime",
        "language": "English",
        "duration_minutes": 118,
        "rating": 8.6,
        "synopsis": "A young FBI cadet must receive the help of an incarcerated and manipulative cannibal killer to help catch another serial killer who skins his victims.",
        "streaming_platforms": "Amazon Prime,Paramount+",
        "poster_url": "https://image.tmdb.org/t/p/w500/uU9xtsAkuJb9KjI4A6Y2xI5T3hH.jpg"
    },
    {
        "title": "Kahaani",
        "year": 2012,
        "director": "Sujoy Ghosh",
        "cast": "Vidya Balan, Nawazuddin Siddiqui, Parambrata Chatterjee",
        "genres": "Thriller,Mystery",
        "language": "Hindi",
        "duration_minutes": 122,
        "rating": 8.1,
        "synopsis": "A pregnant woman searches for her missing husband in Kolkata during the festival of Durga Puja, unraveling a dark conspiracy.",
        "streaming_platforms": "Amazon Prime,Netflix",
        "poster_url": "https://image.tmdb.org/t/p/w500/jN0z3d04dBZx9VuXF3s3gY0P0xH.jpg"
    },
    {
        "title": "Prisoners",
        "year": 2013,
        "director": "Denis Villeneuve",
        "cast": "Hugh Jackman, Jake Gyllenhaal, Viola Davis",
        "genres": "Thriller,Crime",
        "language": "English",
        "duration_minutes": 153,
        "rating": 8.1,
        "synopsis": "When his daughter and her friend go missing, a father takes matters into his own hands while the police pursue multiple leads.",
        "streaming_platforms": "Netflix,Amazon Prime",
        "poster_url": "https://image.tmdb.org/t/p/w500/jLGB3Jz05uUbkjR7AI0YGsXVMwF.jpg"
    },

    # ==================== SCI-FI (10) ====================
    {
        "title": "Inception",
        "year": 2010,
        "director": "Christopher Nolan",
        "cast": "Leonardo DiCaprio, Joseph Gordon-Levitt, Elliot Page",
        "genres": "Sci-Fi,Action",
        "language": "English",
        "duration_minutes": 148,
        "rating": 8.8,
        "synopsis": "A thief who steals corporate secrets through dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O.",
        "streaming_platforms": "Netflix,Amazon Prime",
        "poster_url": "https://image.tmdb.org/t/p/w500/edv5CZvWj09upOsy2Y66wMvCesT.jpg"
    },
    {
        "title": "Interstellar",
        "year": 2014,
        "director": "Christopher Nolan",
        "cast": "Matthew McConaughey, Anne Hathaway, Jessica Chastain",
        "genres": "Sci-Fi,Drama",
        "language": "English",
        "duration_minutes": 169,
        "rating": 8.6,
        "synopsis": "A team of explorers travel through a wormhole in space in an attempt to ensure humanity's survival as Earth becomes uninhabitable.",
        "streaming_platforms": "Paramount+,Amazon Prime",
        "poster_url": "https://image.tmdb.org/t/p/w500/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg"
    },
    {
        "title": "Blade Runner 2049",
        "year": 2017,
        "director": "Denis Villeneuve",
        "cast": "Ryan Gosling, Harrison Ford, Ana de Armas",
        "genres": "Sci-Fi,Drama",
        "language": "English",
        "duration_minutes": 164,
        "rating": 8.0,
        "synopsis": "A young blade runner discovers a long-buried secret that leads him to track down former blade runner Rick Deckard, who has been missing for thirty years.",
        "streaming_platforms": "Netflix,Amazon Prime",
        "poster_url": "https://image.tmdb.org/t/p/w500/gajva2L0rPYkEWjzgFlBXCAVBE5.jpg"
    },
    {
        "title": "Arrival",
        "year": 2016,
        "director": "Denis Villeneuve",
        "cast": "Amy Adams, Jeremy Renner, Forest Whitaker",
        "genres": "Sci-Fi,Drama",
        "language": "English",
        "duration_minutes": 116,
        "rating": 7.9,
        "synopsis": "A linguist works with the military to communicate with alien lifeforms after twelve mysterious spacecraft appear around the world.",
        "streaming_platforms": "Paramount+,Amazon Prime",
        "poster_url": "https://image.tmdb.org/t/p/w500/x2FOnbNpOByr74RiKqAB9TixC7e.jpg"
    },
    {
        "title": "The Matrix",
        "year": 1999,
        "director": "Lana Wachowski, Lilly Wachowski",
        "cast": "Keanu Reeves, Laurence Fishburne, Carrie-Anne Moss",
        "genres": "Sci-Fi,Action",
        "language": "English",
        "duration_minutes": 136,
        "rating": 8.7,
        "synopsis": "When a beautiful stranger leads computer hacker Neo to a forbidding underworld, he discovers the shocking truth—the life he knows is the elaborate deception of an evil cyber-intelligence.",
        "streaming_platforms": "HBO Max,Amazon Prime",
        "poster_url": "https://image.tmdb.org/t/p/w500/f89U3ADr1oiB1s9GkdPOEpXUk5H.jpg"
    },
    {
        "title": "Ex Machina",
        "year": 2014,
        "director": "Alex Garland",
        "cast": "Domhnall Gleeson, Alicia Vikander, Oscar Isaac",
        "genres": "Sci-Fi,Thriller",
        "language": "English",
        "duration_minutes": 108,
        "rating": 7.7,
        "synopsis": "A programmer is selected to participate in a groundbreaking experiment in synthetic intelligence by evaluating the human qualities of a highly advanced humanoid A.I.",
        "streaming_platforms": "Netflix,Amazon Prime",
        "poster_url": "https://image.tmdb.org/t/p/w500/thlLJStfMNcT70MDH85f2g8U7iz.jpg"
    },
    {
        "title": "Eternal Sunshine of the Spotless Mind",
        "year": 2004,
        "director": "Michel Gondry",
        "cast": "Jim Carrey, Kate Winslet, Kirsten Dunst",
        "genres": "Sci-Fi,Romance",
        "language": "English",
        "duration_minutes": 108,
        "rating": 8.3,
        "synopsis": "When their relationship turns sour, a couple undergoes a medical procedure to have each other erased from their memories.",
        "streaming_platforms": "Amazon Prime,Peacock",
        "poster_url": "https://image.tmdb.org/t/p/w500/5Mfc4pMMnKcY7Xhz3VjEcG4fdWw.jpg"
    },
    {
        "title": "Spider-Verse",
        "year": 2018,
        "director": "Bob Persichetti, Peter Ramsey, Rodney Rothman",
        "cast": "Shameik Moore, Jake Johnson, Hailee Steinfeld",
        "genres": "Sci-Fi,Animation",
        "language": "English",
        "duration_minutes": 117,
        "rating": 8.4,
        "synopsis": "Teen Miles Morales becomes the Spider-Man of his dimension and must join with five spider-powered individuals from other dimensions to stop a threat.",
        "streaming_platforms": "Netflix,Amazon Prime",
        "poster_url": "https://image.tmdb.org/t/p/w500/iiZZdoQBFYx1kDlnJTfFbIb0xER.jpg"
    },
    {
        "title": "Dune",
        "year": 2021,
        "director": "Denis Villeneuve",
        "cast": "Timothée Chalamet, Zendaya, Oscar Isaac",
        "genres": "Sci-Fi,Adventure",
        "language": "English",
        "duration_minutes": 155,
        "rating": 8.0,
        "synopsis": "Paul Atreides must travel to the most dangerous planet in the universe to ensure the future of his family and his people.",
        "streaming_platforms": "HBO Max,Amazon Prime",
        "poster_url": "https://image.tmdb.org/t/p/w500/d5NXSklXo0qyIYkgV94XAgMIckC.jpg"
    },
    {
        "title": "Enthiran",
        "year": 2010,
        "director": "Shankar",
        "cast": "Rajinikanth, Aishwarya Rai, Danny Denzongpa",
        "genres": "Sci-Fi,Action",
        "language": "Tamil",
        "duration_minutes": 177,
        "rating": 7.4,
        "synopsis": "An android scientist creates a humanoid robot, but the robot develops its own consciousness and goes rogue.",
        "streaming_platforms": "Amazon Prime,Disney+ Hotstar",
        "poster_url": "https://image.tmdb.org/t/p/w500/t3EmrV61kQcMxK5z2q6s3bVyXYy.jpg"
    },

    # ==================== ROMANCE (12) ====================
    {
        "title": "The Notebook",
        "year": 2004,
        "director": "Nick Cassavetes",
        "cast": "Ryan Gosling, Rachel McAdams, James Garner",
        "genres": "Romance,Drama",
        "language": "English",
        "duration_minutes": 123,
        "rating": 7.8,
        "synopsis": "A poor yet passionate young man falls in love with a rich young woman, giving her a sense of freedom, but they are soon separated because of their social differences.",
        "streaming_platforms": "Netflix,Amazon Prime",
        "poster_url": "https://image.tmdb.org/t/p/w500/qXto6VrN5BctT1LzL9I3Y9zF7nZ.jpg"
    },
    {
        "title": "Pride & Prejudice",
        "year": 2005,
        "director": "Joe Wright",
        "cast": "Keira Knightley, Matthew Macfadyen, Brenda Blethyn",
        "genres": "Romance,Drama",
        "language": "English",
        "duration_minutes": 129,
        "rating": 7.8,
        "synopsis": "Sparks fly when spirited Elizabeth Bennet meets single, rich, and proud Mr. Darcy, who initially finds her less than pleasing.",
        "streaming_platforms": "Amazon Prime,Netflix",
        "poster_url": "https://image.tmdb.org/t/p/w500/lJLrLftShyjHibQ0oS8E4d7Pv6T.jpg"
    },
    {
        "title": "Dilwale Dulhania Le Jayenge",
        "year": 1995,
        "director": "Aditya Chopra",
        "cast": "Shah Rukh Khan, Kajol, Amrish Puri",
        "genres": "Romance,Drama",
        "language": "Hindi",
        "duration_minutes": 190,
        "rating": 8.1,
        "synopsis": "A young Indian man falls in love with a young Indian woman during a trip through Europe, but they face opposition from their traditional families.",
        "streaming_platforms": "Netflix,Amazon Prime",
        "poster_url": "https://image.tmdb.org/t/p/w500/sGm8l6eYhC9uF8pjgf1wJfNnFfA.jpg"
    },
    {
        "title": "Before Sunrise",
        "year": 1995,
        "director": "Richard Linklater",
        "cast": "Ethan Hawke, Julie Delpy, Andrea Eckert",
        "genres": "Romance,Drama",
        "language": "English",
        "duration_minutes": 105,
        "rating": 8.1,
        "synopsis": "A young man and woman meet on a train in Europe and end up spending one evening together in Vienna. Unfortunately, both know that this will probably be their only night together.",
        "streaming_platforms": "Amazon Prime,Paramount+",
        "poster_url": "https://image.tmdb.org/t/p/w500/kagA7MEoHMKzKP4HiMhGfFsWEzf.jpg"
    },
    {
        "title": "Tamasha",
        "year": 2015,
        "director": "Imtiaz Ali",
        "cast": "Ranbir Kapoor, Deepika Padukone",
        "genres": "Romance,Drama",
        "language": "Hindi",
        "duration_minutes": 143,
        "rating": 7.2,
        "synopsis": "A man who has spent his life following society's expectations meets a free-spirited woman who challenges him to live life on his own terms.",
        "streaming_platforms": "Netflix,Amazon Prime",
        "poster_url": "https://image.tmdb.org/t/p/w500/wM6M3sKbV1dKm5GJ8i4e6dFGUfp.jpg"
    },
    {
        "title": "Lost in Translation",
        "year": 2003,
        "director": "Sofia Coppola",
        "cast": "Bill Murray, Scarlett Johansson, Akiko Takeshita",
        "genres": "Romance,Drama",
        "language": "English",
        "duration_minutes": 102,
        "rating": 7.7,
        "synopsis": "A faded movie star and a young woman find an unlikely connection while staying at a Tokyo hotel, both feeling lost and searching for meaning.",
        "streaming_platforms": "Paramount+,Amazon Prime",
        "poster_url": "https://image.tmdb.org/t/p/w500/5AphYjZGmEYbRPpG3oSB75SN3p9.jpg"
    },
    {
        "title": "Crazy, Stupid, Love.",
        "year": 2011,
        "director": "Glenn Ficarra, John Requa",
        "cast": "Steve Carell, Ryan Gosling, Julianne Moore",
        "genres": "Romance,Comedy",
        "language": "English",
        "duration_minutes": 118,
        "rating": 7.3,
        "synopsis": "A middle-aged husband's life changes dramatically when his wife asks him for a divorce. He seeks to rediscover his manhood with the help of a young bachelor.",
        "streaming_platforms": "Hulu,Amazon Prime",
        "poster_url": "https://image.tmdb.org/t/p/w500/tBrMnQv8q25w0YxQHqRiNPz7Xgp.jpg"
    },
    {
        "title": "Love Actually",
        "year": 2003,
        "director": "Richard Curtis",
        "cast": "Hugh Grant, Liam Neeson, Colin Firth",
        "genres": "Romance,Comedy",
        "language": "English",
        "duration_minutes": 135,
        "rating": 7.6,
        "synopsis": "Follows the lives of eight very different couples in dealing with their love lives in various loosely interrelated tales all set during a frantic month before Christmas in London.",
        "streaming_platforms": "Amazon Prime,Peacock",
        "poster_url": "https://image.tmdb.org/t/p/w500/3S1PnXJa74S1h2pcMG5c0p5jvh.jpg"
    },
    {
        "title": "Dev D",
        "year": 2009,
        "director": "Anurag Kashyap",
        "cast": "Abhay Deol, Kalki Koechlin, Mahie Gill",
        "genres": "Romance,Drama",
        "language": "Hindi",
        "duration_minutes": 146,
        "rating": 7.4,
        "synopsis": "A modern-day adaptation of Devdas, following a self-destructive man who drowns himself in alcohol after losing the woman he loves.",
        "streaming_platforms": "Netflix,Amazon Prime",
        "poster_url": "https://image.tmdb.org/t/p/w500/pU8aEBwYJxB7fZY2WnKL5w6hF3X.jpg"
    },
    {
        "title": "My Sassy Girl",
        "year": 2001,
        "director": "Kwak Jae-yong",
        "cast": "Jun Ji-hyun, Cha Tae-hyun",
        "genres": "Romance,Comedy",
        "language": "Korean",
        "duration_minutes": 137,
        "rating": 7.7,
        "synopsis": "A young man falls for a beautiful but unpredictable woman who he initially rescues from a subway platform, leading to an unconventional love story.",
        "streaming_platforms": "Netflix,Viki",
        "poster_url": "https://image.tmdb.org/t/p/w500/pFBR2m7vHPA1JtbrD8Q0Yd6K7pG.jpg"
    },
    {
        "title": "Call Me by Your Name",
        "year": 2017,
        "director": "Luca Guadagnino",
        "cast": "Timothée Chalamet, Armie Hammer, Michael Stuhlbarg",
        "genres": "Romance,Drama",
        "language": "English",
        "duration_minutes": 132,
        "rating": 7.8,
        "synopsis": "In 1983, a 17-year-old boy falls in love with a visiting American scholar staying at his family's villa in Northern Italy.",
        "streaming_platforms": "Amazon Prime,Hulu",
        "poster_url": "https://image.tmdb.org/t/p/w500/koVtMkYaSH1rIm1k6M7eY18BWNO.jpg"
    },
    {
        "title": "Jeans",
        "year": 1998,
        "director": "S. Shankar",
        "cast": "Prashanth, Aishwarya Rai, Nassar",
        "genres": "Romance,Comedy",
        "language": "Tamil",
        "duration_minutes": 165,
        "rating": 6.5,
        "synopsis": "A man and woman fall in love, but their families clash over cultural differences and expectations, leading to a humorous battle of wills.",
        "streaming_platforms": "Amazon Prime,Disney+ Hotstar",
        "poster_url": "https://image.tmdb.org/t/p/w500/hK3sVaL6WUkM8zFHx8VqkHSv5bM.jpg"
    },
]


def seed_database():
    init_db()
    db = SessionLocal()
    try:
        existing_count = db.query(MovieDB).count()
        if existing_count > 0:
            print(f"Database already has {existing_count} movies. Skipping seed.")
            return

        for idx, movie_data in enumerate(MOVIES, start=1):
            movie = MovieDB(id=idx, **movie_data)
            db.add(movie)

        db.commit()
        print(f"Successfully seeded {len(MOVIES)} movies into the database.")
    except Exception as e:
        db.rollback()
        print(f"Error seeding database: {e}")
        raise
    finally:
        db.close()


if __name__ == "__main__":
    seed_database()
